### ISSUE TITLE
Doesn't look quite the same on mac

### ISSUE THREAD

**Issue by CodisRedding** [goatslacker/mango.vim#10]
Here's my setup: [~/.vim/.vimrc](http://pastebin.com/V2eaY7a9)

Here's a screen shot: [pic](http://screencast.com/t/d2PokNTQUA)

Any help would be great. Thanks

**Comment by saamalik** [comment]
@fourq you're the first person I've come across that shares the same name (Assad with two _s'_) as my brother ( _Assad_ ).

Regarding your problem, try setting `background=dark` in your vimrc:

```
set background=dark
colorscheme mango
```

**Comment by CodisRedding** [comment]
@saamalik well you're the first person to tell me that. I've have any good conversations regarding our last name. Ever since I was a kid. 

I have background already set to dark and I manually set the colorscheme while in vim and in .vimrc, but nothing.

**Comment by goatslacker** [comment]
Is that tmux or screen? Are you using mac vim?

Can you try on a terminal that supports 256 colors with just regular vim. Also what javascript vim file are you using? Default? I recommend pangloss/vim-javascript

You can also try removing all your pathogen bundles just to make sure they're not conflicting.

**Comment by CodisRedding** [comment]
I ended up installing the the very lated version via brew, and then running an update on all bundles did the trick. I'm not sure what was causing the issue. I still have the old version installed so I can cherry pic the bundles to see if I can't figure out the cause. Thanks everyone.
