### ISSUE TITLE
Broken in Windows :( 

### ISSUE THREAD

**Issue by mikey-** [goatslacker/mango.vim#7]
Hi,

I tried this out on my windows vim and I was surprised to see the colours are all messed up ;A; 

I installed mango through vundle

<a href="http://i48.tinypic.com/3496tdh.png">Click here to see it!</a>

^ I thought this might have been caused by me as i had previously messed with the colours but I have since reverted them all to default (as you can see from the terminal window in the background)

here is my _vimrc:

<pre>
set nocompatible               " be iMprovedg:nerdtree_tabs_open_on_console_startup
 filetype off                   " required!g:nerdtree_tabs_open_on_console_startup

 set rtp+=~/.vim/bundle/vundle/
 call vundle#rc()

 " let Vundle manage Vundle
 " required!
 Bundle 'gmarik/vundle'

 " My Bundles here:
 "
 " original repos on github
 Bundle 'tpope/vim-fugitive'
 Bundle 'tpope/vim-rails.git'
 Bundle 'scrooloose/nerdtree.git'
 Bundle 'jistr/vim-nerdtree-tabs.git'
 Bundle 'hoffstein/vim-tsql.git'
 Bundle 'goatslacker/mango.vim'

 " vim-scripts repos
 Bundle 'L9'
 " non github repos
 " ...

 filetype plugin indent on     " required!
 "
 " Brief help
 " :BundleList          - list configured bundles
 " :BundleInstall(!)    - install(update) bundles
 " :BundleSearch(!) foo - search(or refresh cache first) for foo
 " :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
 "
 " see :h vundle for more details or wiki for FAQ
 " NOTE: comments after Bundle command are not allowed..

map <F3> <Ctrl-ww>
map <F2> <plug>NERDTreeTabsToggle<CR>
let g:nerdtree_tabs_open_on_console_startup=1
let g:sql_type_default = "sqlserver"
:set softtabstop=4
:set shiftwidth=4
:set expandtab

" syntax highlighting
 set background=dark
 syntax on
 color mango
</pre>

**Comment by saamalik** [comment]
It works great for me in Windows. Though I'm using Cygwin.
